"use client";

import { createContext, useContext, useState, ReactNode } from "react";

type Language = "en" | "ml" | "ta" | "hi" | "kn";

interface Translations {
    [key: string]: {
        [key: string]: string;
    };
}

export const translations: Translations = {
    en: {
        "nav-home": "Home",
        "nav-labor": "Labor & Logistics",
        "nav-stock": "Inputs & Stock",
        "nav-crop": "Crop Health",
        "farmer-portal": "Farmer Portal",
        "labor-title": "Harvest Season Optimization",
        "labor-sub": "Manage your workforce and synchronized logistics in one place.",
        "worker-match": "Worker Matching",
        "worker-sub": "Match with verified workers based on your farm location and harvest schedule.",
        "btn-find": "Find Workers",
        "transport-title": "Valley-to-Hill Transport",
        "transport-sub": "Shared mini-buses and jeeps for workforce mobilization.",
        "btn-schedule": "Schedule Carpool",
        "qr-title": "QR Check-in & Credits",
        "qr-sub": "Fast attendance and co-op credit subsidies for transport.",
        "qr-scan": "Scan worker QR to confirm arrival",
        "stock-title": "Agrochemicals & Stock",
        "stock-sub": "Real-time availability of fertilizers and essential medicines.",
        "inventory-title": "Live Inventory Tracking",
        "th-item": "Item Name",
        "th-status": "Status",
        "th-source": "Nearest Source",
        "th-option": "Option",
        "shop-title": "Shop Locator",
        "shop-sub": "Find authorized dealers within 10km radius.",
        "crop-title": "Crop Health & Diagnostics",
        "crop-sub": "Detect, identify, and manage diseases in your cardamom plantation.",
        "ai-scan-title": "AI Disease Scan",
        "ai-scan-sub": "Upload or take a photo of leaves, stems, or capsules to detect disease damage.",
        "btn-scan": "Start Diagnostic Scan",
        "lib-title": "Disease Library",
        "lib-sub": "Comprehensive guide to cardamom diseases and curative measures.",
        "dis-katte": "Katte (Mosaic Disease)",
        "dis-azhukal": "Azhukal (Capsule Rot)",
        "dis-rhizome": "Rhizome Rot management",
        "path-title": "Pathology Support",
        "path-sub": "Connect with registered plant pathologists for soil testing and custom spray schedules.",
        "btn-consult": "Consult Specialist",
        "worker-portal": "Worker Portal",
        "portal-farmer": "Farmer View",
        "portal-worker": "Worker View",
        "available-jobs": "Available Works",
        "job-sub": "Find and apply for harvest and maintenance tasks near you.",
        "btn-apply": "Apply Now",
        "job-location": "Location",
        "job-pay": "Pay Range",
        "profile-title": "Farmer Profile",
        "profile-name": "Name",
        "profile-location": "Farm Location",
        "profile-land": "Land Size",
        "profile-contact": "Contact",
        "profile-member-since": "Member Since",
        "farmer-name": "Thomas Mathew",
        "farmer-location": "Vandanmedu, Idukki",
        "farmer-land": "12 Acres (Cardamom)",
        "farmer-contact": "+91 9845X XXXXX",
        "farmer-member-since": "June 2021",
        "portal-shopkeeper": "Shopkeeper View",
        "role-selection": "Select Your Role",
        "role-farmer": "Farmer",
        "role-worker": "Worker",
        "role-shopkeeper": "Shopkeeper",
        "btn-login": "Sign In",
        "btn-signup": "Create Account",
        "btn-logout": "Sign Out",
        "email-label": "Email Address",
        "password-label": "Password",
        "toggle-signup": "Don't have an account? Sign Up",
        "toggle-login": "Already have an account? Sign In",
        "auth-title": "Join Harvest Hive",
        "home-title": "The Cardamom Ecosystem",
        "home-sub": "Empowering the agrarian community of the Western Ghats with technology.",
        "about-cardamom-title": "Queen of Spices",
        "about-cardamom-text": "Cardamom, known as the 'Queen of Spices', is the heart of our region's economy. Growing them requires precision, care, and timely intervention.",
        "explore-features": "Explore Our Features",
        "home-labor-desc": "Manage laborers and transport with ease.",
        "home-stock-desc": "Keep track of fertilizers and pesticides.",
        "home-crop-desc": "Protect your yield with AI diagnostics.",
        "btn-get-started": "Get Started Now",
        "already-member": "Already a member?"
    },
    ml: {
        "nav-home": "ഹോം",
        "nav-labor": "തൊഴിലാളികളും ലോജിസ്റ്റിക്സും",
        "nav-stock": "വളങ്ങളും മരുന്നുകളും",
        "nav-crop": "വിള ആരോഗ്യം",
        "farmer-portal": "കർഷക പോർട്ടൽ",
        "labor-title": "വിളവെടുപ്പ് കാലം ക്രമീകരിക്കാം",
        "labor-sub": "തൊഴിലാളികളെയും യാത്രയും ഒരിടത്ത് നിയന്ത്രിക്കുക.",
        "worker-match": "തൊഴിലാളികൾ",
        "worker-sub": "നിങ്ങളുടെ കൃഷിയിടത്തിനടുത്തുള്ള തൊഴിലാളികളെ കണ്ടെത്തുക.",
        "btn-find": "തൊഴിലാളികളെ തിരയുക",
        "transport-title": "യാത്രാ സൗകര്യം",
        "transport-sub": "തോട്ടങ്ങളിലേക്കുള്ള ജീപ്പ്/ബസ് സർവീസുകൾ.",
        "btn-schedule": "യാത്ര ബുക്ക് ചെയ്യുക",
        "qr-title": "ക്യുആർ ചെക്ക്-ഇൻ",
        "qr-sub": "പെട്ടെന്നുള്ള ഹാജർ രേഖപ്പെടുത്തലും സബ്‌സിഡിയും.",
        "qr-scan": "ഹാജർ രേഖപ്പെടുത്താൻ സ്കാൻ ചെയ്യുക",
        "stock-title": "വളങ്ങളും സ്റ്റോക്കും",
        "stock-sub": "വളങ്ങളുടെയും മരുന്നുകളുടെയും ലഭ്യത അറിയുക.",
        "inventory-title": "സ്റ്റോക്ക് വിവരങ്ങൾ",
        "th-item": "സാധനം",
        "th-status": "നില",
        "th-source": "സ്ഥലം",
        "th-option": "രീതി",
        "shop-title": "ഷോപ്പ് ലൊക്കേറ്റർ",
        "shop-sub": "അടുത്തുള്ള ഷോപ്പുകൾ കണ്ടെത്തുക.",
        "crop-title": "വിള ആരോഗ്യം",
        "crop-sub": "രോഗങ്ങൾ തിരിച്ചറിയാനും നിയന്ത്രിക്കാനും സഹായിക്കുന്നു.",
        "ai-scan-title": "AI രോഗ പരിശോധന",
        "ai-scan-sub": "ഇലയുടെയോ കായയുടെയോ ഫോട്ടോ എടുത്തു രോഗം തിരിച്ചറിയുക.",
        "btn-scan": "പരിശോധന തുടങ്ങുക",
        "lib-title": "രോഗവിവരങ്ങൾ",
        "lib-sub": "രോഗങ്ങളെയും അവയ്ക്കുള്ള ചികിത്സയെയും കുറിച്ചുള്ള വിവരങ്ങൾ.",
        "dis-katte": "കറ്റെ രോഗം",
        "dis-azhukal": "അഴുകൽ രോഗം",
        "dis-rhizome": "ചുവടഴുകൽ നിയന്ത്രണം",
        "path-title": "വിദഗ്ദ്ധ സഹായം",
        "path-sub": "മണ്ണ് പരിശോധനയ്ക്കും വിദഗ്ദ്ധ ഉപദേശത്തിനും ബന്ധപ്പെടുക.",
        "btn-consult": "വിദഗ്ദ്ധനെ കാണുക",
        "worker-portal": "തൊഴിലാളി പോർട്ടൽ",
        "portal-farmer": "കർഷകൻ",
        "portal-worker": "തൊഴിലാളി",
        "available-jobs": "ലഭ്യമായ ജോലികൾ",
        "job-sub": "നിങ്ങളുടെ അടുത്തുള്ള ജോലികൾ കണ്ടെത്തുക.",
        "btn-apply": "അപേക്ഷിക്കുക",
        "job-location": "സ്ഥലം",
        "job-pay": "കൂലി",
        "profile-title": "കർഷക പ്രൊഫൈൽ",
        "profile-name": "പേര്",
        "profile-location": "സ്ഥലം",
        "profile-land": "കൃഷിസ്ഥലം",
        "profile-contact": "ഫോൺ",
        "profile-member-since": "അംഗമായത്",
        "farmer-name": "തോമസ് മാത്യു",
        "farmer-location": "വണ്ടൻമേട്, ഇടുക്കി",
        "farmer-land": "12 ഏക്കർ (ഏലം)",
        "farmer-contact": "+91 9845X XXXXX",
        "farmer-member-since": "ജൂൺ 2021",
        "portal-shopkeeper": "വ്യാപാരി",
        "role-selection": "റോൾ തിരഞ്ഞെടുക്കുക",
        "role-farmer": "കർഷകൻ",
        "role-worker": "തൊഴിലാളി",
        "role-shopkeeper": "വ്യാപാരി",
        "btn-login": "ലോഗിൻ ചെയ്യുക",
        "btn-signup": "അക്കൗണ്ട് ഉണ്ടാക്കുക",
        "btn-logout": "പുറത്തുകടക്കുക",
        "email-label": "ഇമെയിൽ വിലാസം",
        "password-label": "പാസ്‌വേഡ്",
        "toggle-signup": "അക്കൗണ്ട് ഇല്ലേ? സൈൻ അപ്പ് ചെയ്യുക",
        "toggle-login": "അക്കൗണ്ട് ഉണ്ടോ? ലോഗിൻ ചെയ്യുക",
        "auth-title": "ഹാർവാസ്റ്റ് ഹൈവ് ലോഗിൻ",
        "home-title": "ഏലം ഇക്കോസിസ്റ്റം",
        "home-sub": "സാങ്കേതികവിദ്യയിലൂടെ പശ്ചിമഘട്ടത്തിലെ കാർഷിക സമൂഹത്തെ ശാക്തീകരിക്കുന്നു.",
        "about-cardamom-title": "വ്യഞ്ജനങ്ങളുടെ റാണി",
        "about-cardamom-text": "വ്യഞ്ജനങ്ങളുടെ റാണി എന്നറിയപ്പെടുന്ന ഏലം നമ്മുടെ പ്രദേശത്തെ സമ്പദ്‌വ്യവസ്ഥയുടെ ഹൃദയമാണ്. അത് വളർത്താൻ കൃത്യതയും പരിചരണവും സമയബന്ധിതമായ ഇടപെടലും ആവശ്യമാണ്.",
        "explore-features": "സവിശേഷതകൾ പര്യവേക്ഷണം ചെയ്യുക",
        "home-labor-desc": "തൊഴിലാളികളെയും യാത്രാ സൗകര്യങ്ങളെയും എളുപ്പത്തിൽ നിയന്ത്രിക്കുക.",
        "home-stock-desc": "വളങ്ങളുടെയും കീടനാശിനികളുടെയും ലഭ്യത പരിശോധിക്കുക.",
        "home-crop-desc": "AI ഡയഗ്നോസ്റ്റിക്സ് ഉപയോഗിച്ച് നിങ്ങളുടെ വിളയെ സംരക്ഷിക്കുക.",
        "btn-get-started": "ഇപ്പോൾ ആരംഭിക്കുക",
        "already-member": "നിങ്ങൾ ഇതിനകം അംഗമാണോ?"
    },
    ta: {
        "nav-home": "முகப்பு",
        "nav-labor": "தொழிலாளர் & போக்குவரத்து",
        "nav-stock": "உரங்கள் & இருப்பு",
        "nav-crop": "பயிர் ஆரோக்கியம்",
        "farmer-portal": "விவசாயி போர்டல்",
        "labor-title": "அறுவடை கால மேலாண்மை",
        "labor-sub": "உங்கள் தொழிலாளர்கள் மற்றும் போக்குவரத்தை ஒரே இடத்தில் நிர்வகிக்கவும்.",
        "worker-match": "தொழிலாளர் தேடல்",
        "worker-sub": "உங்கள் தோட்ட இருப்பிடத்தின் அடிப்படையில் தொழிலாளர்களைக் கண்டறியவும்.",
        "btn-find": "வேலையாட்களைத் தேடு",
        "transport-title": "மலைப்பகுதி போக்குவரத்து",
        "transport-sub": "தோட்டங்களுக்கான ஜீப் மற்றும் வாகன வசதிகள்.",
        "btn-schedule": "வாகனம் முன்பதிவு செய்",
        "qr-title": "QR வருகை பதிவு",
        "qr-sub": "விரைவான வருகைப் பதிவு மற்றும் மானியச் சரிபார்ப்பு.",
        "qr-scan": "பதிவு செய்ய QR ஐ ஸேன் செய்யவும்",
        "stock-title": "உரங்கள் மற்றும் இருப்பு",
        "stock-sub": "உரங்கள் மற்றும் அத்தியாவசிய மருந்துகளின் இருப்பு விவரங்கள்.",
        "inventory-title": "இருப்பு விவரங்கள்",
        "th-item": "பொருள்",
        "th-status": "நிலை",
        "th-source": "கிடைக்கும் இடம்",
        "th-option": "தேர்வு",
        "shop-title": "கடை இருப்பிடம்",
        "shop-sub": "அருகிலுள்ள அங்கீகரிக்கப்பட்ட கடைகளைக் கண்டறியவும்.",
        "crop-title": "பயிர் ஆரோக்கியம் & கண்டறிதல்",
        "crop-sub": "உங்கள் ஏலக்காய் தோட்டத்தில் நோய்களைக் கண்டறிந்து நிர்வகிக்கவும்.",
        "ai-scan-title": "AI நோய் கண்டறிதல்",
        "ai-scan-sub": "புகைப்படம் எடுத்து நோயைத் தானாகக் கண்டறியவும்.",
        "btn-scan": "சோதனையைத் தொடங்கு",
        "lib-title": "நோய் தகவல் மையம்",
        "lib-sub": "நோய்கள் மற்றும் அவற்றின் நிவாரண முறைகள் பற்றிய கையேடு.",
        "dis-katte": "கட்டே நோய்",
        "dis-azhukal": "அழுகல் நோய்",
        "dis-rhizome": "வேர் அழுகல் நோய் மேலாண்மை",
        "path-title": "நிபுணர் உதவி",
        "path-sub": "மண் பரிசோதனை மற்றும் ஆலோசனைகளுக்கு நிபுணரைத் தொடர்பு கொள்ளவும்.",
        "btn-consult": "நிபுணரை அணுகவும்",
        "worker-portal": "தொழிலாளர் போர்டல்",
        "portal-farmer": "விவசாயி பார்வை",
        "portal-worker": "தொழிலாளர் பார்வை",
        "available-jobs": "கிடைக்கக்கூடிய வேலைகள்",
        "job-sub": "உங்களுக்கு அருகிலுள்ள வேலைகளைக் கண்டறியவும்.",
        "btn-apply": "விண்ணப்பிக்கவும்",
        "job-location": "இடம்",
        "job-pay": "ஊதியம்",
        "profile-title": "விவசாயி சுயவிவரம்",
        "profile-name": "பெயர்",
        "profile-location": "தோட்டத்தின் இடம்",
        "profile-land": "நிலத்தின் அளவு",
        "profile-contact": "தொடர்பு",
        "profile-member-since": "உறுப்பினர் காலம்",
        "farmer-name": "தாமஸ் மேத்யூ",
        "farmer-location": "வந்தன்மேடு, இடுக்கி",
        "farmer-land": "12 ஏக்கர் (ஏலக்காய்)",
        "farmer-contact": "+91 9845X XXXXX",
        "farmer-member-since": "ஜூன் 2021",
        "portal-shopkeeper": "வணிகர் பார்வை",
        "role-selection": "உங்கள் நிலையைத் தேர்வுசெய்க",
        "role-farmer": "விவசாயி",
        "role-worker": "தொழிலாளர்",
        "role-shopkeeper": "வணிகர்",
        "btn-login": "உள்நுழைக",
        "btn-signup": "கணக்கை உருவாக்குக",
        "btn-logout": "வெளியேறவும்",
        "email-label": "மின்னஞ்சல் முகவரி",
        "password-label": "கடவுச்சொல்",
        "toggle-signup": "கணக்கு இல்லையா? பதிவு செய்யவும்",
        "toggle-login": "ஏற்கனவே கணக்கு உள்ளதா? உள்நுழைக",
        "auth-title": "ஹார்வெஸ்ட் ஹைவ் இணையுங்கள்",
        "home-title": "ஏலக்காய் சுற்றுச்சூழல்",
        "home-sub": "தொழில்நுட்பத்தின் மூலம் மேற்குத் தொடர்ச்சி மலையின் விவசாய சமூகத்தை மேம்படுத்துதல்.",
        "about-cardamom-title": "நறுமணப் பொருட்களின் ராணி",
        "about-cardamom-text": "நறுமணப் பொருட்களின் ராணி என்று அழைக்கப்படும் ஏலக்காய் நமது பிராந்தியத்தின் பொருளாதாரத்தின் இதயமாகும். அவற்றை வளர்ப்பதற்கு துல்லியம், கவனிப்பு மற்றும் சரியான நேரத்தில் தலையீடு தேவைப்படுகிறது.",
        "explore-features": "எங்கள் அம்சங்களை ஆராயுங்கள்",
        "home-labor-desc": "தொழிலாளர்கள் மற்றும் போக்குவரத்தை எளிதாக நிர்வகிக்கவும்.",
        "home-stock-desc": "உரங்கள் மற்றும் பூச்சிக்கொல்லிகளைக் கண்காணிக்கவும்.",
        "home-crop-desc": "AI நோயறிதல் மூலம் உங்கள் விளைச்சலைப் பாதுகாக்கவும்.",
        "btn-get-started": "இப்போது தொடங்குங்கள்",
        "already-member": "ஏற்கனவே உறுப்பினரா?"
    },
    hi: {
        "nav-home": "होम",
        "nav-labor": "श्रम और रसद",
        "nav-stock": "इनपुट और स्टॉक",
        "nav-crop": "फसल स्वास्थ्य",
        "farmer-portal": "किसान पोर्टल",
        "labor-title": "कटाई के मौसम का अनुकूलन",
        "labor-sub": "एक ही स्थान पर अपने कार्यबल और रसद का प्रबंधन करें।",
        "worker-match": "श्रमिक मिलान",
        "worker-sub": "अपने खेत के स्थान के आधार पर श्रमिकों का मिलान करें।",
        "btn-find": "श्रमिक खोजें",
        "transport-title": "पहाड़ी परिवहन",
        "transport-sub": "कार्यबल के लिए साझा मिनी-बसें और जीप।",
        "btn-schedule": "यात्रा निर्धारित करें",
        "qr-title": "क्यूआर चेक-इन",
        "qr-sub": "त्वरित उपस्थिति और परिवहन सब्सिडी।",
        "qr-scan": "आगमन की पुष्टि के लिए स्कैन करें",
        "stock-title": "खाद और दवाओं का स्टॉक",
        "stock-sub": "खाद और दवाओं की रीयल-टाइम उपलब्धता।",
        "inventory-title": "इन्वेंट्री ट्रैकिंग",
        "th-item": "सामग्री",
        "th-status": "स्थिति",
        "th-source": "स्रोत",
        "th-option": "विकल्प",
        "shop-title": "दुकान खोजें",
        "shop-sub": "10 किमी के भीतर अधिकृत डीलर खोजें।",
        "crop-title": "फसल स्वास्थ्य",
        "crop-sub": "बीमारियों का पता लगाएं और प्रबंधित करें।",
        "ai-scan-title": "AI रोग स्कैन",
        "ai-scan-sub": "फोटो लेकर बीमारी का निदान करें।",
        "btn-scan": "स्कैन शुरू करें",
        "lib-title": "रोग पुस्तकालय",
        "lib-sub": "रोगों और उपचारात्मक उपायों के लिए विस्तृत मार्गदर्शिका।",
        "dis-katte": "कट्टे (मोज़ेक रोग)",
        "dis-azhukal": "अझुकल (कैप्सूल सड़न)",
        "dis-rhizome": "प्रकंद सड़न प्रबंधन",
        "path-title": "विशेषज्ञ सहायता",
        "path-sub": "मिट्टी परीक्षण और सलाह के लिए विशेषज्ञों से जुड़ें।",
        "btn-consult": "विशेषज्ञ से मिलें",
        "worker-portal": "श्रमिक पोर्टल",
        "portal-farmer": "किसान दृश्य",
        "portal-worker": "श्रमिक दृश्य",
        "available-jobs": "उपलब्ध कार्य",
        "job-sub": "अपने आस-पास कटाई और रखरखाव के कार्य खोजें और आवेदन करें।",
        "btn-apply": "अभी आवेदन करें",
        "job-location": "स्थान",
        "job-pay": "वेतन",
        "profile-title": "किसान प्रोफ़ाइल",
        "profile-name": "नाम",
        "profile-location": "खेत का स्थान",
        "profile-land": "भूमि का आकार",
        "profile-contact": "संपर्क",
        "profile-member-since": "सदस्यता की तिथि",
        "farmer-name": "थॉमस मैथ्यू",
        "farmer-location": "वंदनमेडु, इडुक्की",
        "farmer-land": "12 एकड़ (इलायची)",
        "farmer-contact": "+91 9845X XXXXX",
        "farmer-member-since": "जून 2021",
        "portal-shopkeeper": "दुकानदार दृश्य",
        "role-selection": "अपनी भूमिका चुनें",
        "role-farmer": "किसान",
        "role-worker": "श्रमिक",
        "role-shopkeeper": "दुकानदार",
        "btn-login": "साइन इन करें",
        "btn-signup": "अकाउंट बनाएं",
        "btn-logout": "साइन आउट",
        "email-label": "ईमेल पता",
        "password-label": "पासवर्ड",
        "toggle-signup": "अकाउंट नहीं है? साइन अप करें",
        "toggle-login": "पहले से अकाउंट है? साइन इन करें",
        "auth-title": "हार्वेस्ट हाइव से जुड़ें",
        "home-title": "इलायची पारिस्थितिकी तंत्र",
        "home-sub": "प्रौद्योगिकी के साथ पश्चिमी घाट के कृषि समुदाय को सशक्त बनाना।",
        "about-cardamom-title": "मसालों की रानी",
        "about-cardamom-text": "इलायची, जिसे 'मसालों की रानी' के रूप में जाना जाता है, हमारे क्षेत्र की अर्थव्यवस्था का हृदय है। उन्हें उगाने के लिए सटीकता, देखभाल और समय पर हस्तक्षेप की आवश्यकता होती है।",
        "explore-features": "हमारी विशेषताओं का अन्वेषण करें",
        "home-labor-desc": "श्रमिकों और परिवहन को आसानी से प्रबंधित करें।",
        "home-stock-desc": "उर्वरकों और कीटनाशकों पर नज़र रखें।",
        "home-crop-desc": "AI डायग्नोस्टिक्स के साथ अपनी उपज की रक्षा करें।",
        "btn-get-started": "अभी शुरू करें",
        "already-member": "पहले से ही सदस्य हैं?"
    },
    kn: {
        "nav-home": "ಮನೆ",
        "nav-labor": "ಕಾರ್ಮಿಕರು ಮತ್ತು ಸಾರಿಗೆ",
        "nav-stock": "ಪರಿಕರಗಳು ಮತ್ತು ದಾಸ್ತಾನು",
        "nav-crop": "ಬೆಳೆ ಆರೋಗ್ಯ",
        "farmer-portal": "ರೈತ ಪೋರ್ಟಲ್",
        "labor-title": "ಕೊಯ್ಲು ಅವಧಿಯ ನಿರ್ವಹಣೆ",
        "labor-sub": "ನಿಮ್ಮ ಕಾರ್ಮಿಕರನ್ನು ಮತ್ತು ಸಾರಿಗೆಯನ್ನು ಒಂದೇ ಸ್ಥಳದಲ್ಲಿ ನಿರ್ವಹಿಸಿ.",
        "worker-match": "ಕಾರ್ಮಿಕರ ಹುಡುಕಾಟ",
        "worker-sub": "ನಿಮ್ಮ ತೋಟದ ಸ್ಥಳದ ಆಧಾರದ ಮೇಲೆ ಕಾರ್ಮಿಕರನ್ನು ಹುಡುಕಿ.",
        "btn-find": "ಕಾರ್ಮಿಕರನ್ನು ಹುಡುಕಿ",
        "transport-title": "ಬೆಟ್ಟದ ಸಾರಿಗೆ",
        "transport-sub": "ಕಾರ್ಮಿಕರಿಗಾಗಿ ಹಂಚಿಕೆಯ ಜೀಪ್ ಮತ್ತು ಬಸ್ ಸೌಲಭ್ಯ.",
        "btn-schedule": "ಸಾರಿಗೆ ಬುಕ್ ಮಾಡಿ",
        "qr-title": "QR ಹಾಜರಾತಿ",
        "qr-sub": "ತ್ವರಿತ ಹಾಜರಾತಿ ಮತ್ತು ಸಾರಿಗೆ ಸಬ್ಸಿಡಿ.",
        "qr-scan": "ಹಾಜರಾತಿಗಾಗಿ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ",
        "stock-title": "ಗೊಬ್ಬರ ಮಾಹಿತಿ",
        "stock-sub": "ಗೊಬ್ಬರ ಮತ್ತು ಅಗತ್ಯ ಔಷಧಿಗಳ ಲಭ್ಯತೆ.",
        "inventory-title": "ದಾಸ್ತಾನು ಮಾಹಿತಿ",
        "th-item": "ವಸ್ತು",
        "th-status": "ಸ್ಥಿತಿ",
        "th-source": "ಮೂಲ",
        "th-option": "ಆಯ್ಕೆ",
        "shop-title": "ಅಂಗಡಿ ಮಾಹಿತಿ",
        "shop-sub": "ಹತ್ತಿರದ ಅಧಿಕೃತ ವಿತರಕರನ್ನು ಪತ್ತೆಹಚ್ಚಿ.",
        "crop-title": "ಬೆಳೆ ಆರೋಗ್ಯ",
        "crop-sub": "ನಿಮ್ಮ ತೋಟದಲ್ಲಿ ರೋಗಗಳನ್ನು ಪತ್ತೆಹಚ್ಚಿ.",
        "ai-scan-title": "AI ರೋಗ ತಪಾಸಣೆ",
        "ai-scan-sub": "ಫೋಟೋ ಮೂಲಕ ರೋಗವನ್ನು ಪತ್ತೆಹಚ್ಚಿ.",
        "btn-scan": "ತಪಾಸಣೆ ಪ್ರಾರಂಭಿಸಿ",
        "lib-title": "ರೋಗ ಮಾಹಿತಿ ಕೇಂದ್ರ",
        "lib-sub": "ರೋಗಗಳು ಮತ್ತು ಅವುಗಳ ಪರಿಹಾರಗಳ ಮಾಹಿತಿ.",
        "dis-katte": "ಕಟ್ಟೆ ರೋಗ",
        "dis-azhukal": "ಅಳಕು ರೋಗ",
        "dis-rhizome": "ಗೆಡ್ಡೆ ಕೊಳೆತ ನಿರ್ವಹಣೆ",
        "path-title": "ತಜ್ಞರ ನೆರವು",
        "path-sub": "ಮಣ್ಣು ಪರೀಕ್ಷೆ ಮತ್ತು ಸಲಹೆಗಾಗಿ ತಜ್ಞರನ್ನು ಸಂಪರ್ಕಿಸಿ.",
        "btn-consult": "ತಜ್ಞರನ್ನು ಸಂಪರ್ಕಿಸಿ",
        "worker-portal": "ಕಾರ್ಮಿಕರ ಪೋರ್ಟಲ್",
        "portal-farmer": "ರೈತರ ನೋಟ",
        "portal-worker": "ಕಾರ್ಮಿಕರ ನೋಟ",
        "available-jobs": "ಲಭ್ಯವಿರುವ ಕೆಲಸಗಳು",
        "job-sub": "ನಿಮ್ಮ ಹತ್ತಿರದ ಕೆಲಸಗಳನ್ನು ಹುಡುಕಿ ಮತ್ತು ಅರ್ಜಿ ಸಲ್ಲಿಸಿ.",
        "btn-apply": "ಈಗ ಅನ್ವಯಿಸು",
        "job-location": "ಸ್ಥಳ",
        "job-pay": "ವೇತನ",
        "profile-title": "ರೈತರ ಪ್ರೊಫೈಲ್",
        "profile-name": "ಹೆಸರು",
        "profile-location": "ತೋಟದ ಸ್ಥಳ",
        "profile-land": "ಭೂಮಿಯ ಗಾತ್ರ",
        "profile-contact": "ಸಂಪರ್ಕ",
        "profile-member-since": "ಸದಸ್ಯತ್ವದ ಅವಧಿ",
        "farmer-name": "ಥಾಮಸ್ ಮ್ಯಾಥ್ಯೂ",
        "farmer-location": "ವಂದನ್ ಮೇಡು, ಇಡುಕ್ಕಿ",
        "farmer-land": "12 ಎಕರೆ (ಏಲಕ್ಕಿ)",
        "farmer-contact": "+91 9845X XXXXX",
        "farmer-member-since": "ಜೂನ್ 2021",
        "portal-shopkeeper": "ವ್ಯಾಪಾರಿ ನೋಟ",
        "role-selection": "ನಿಮ್ಮ ಪಾತ್ರವನ್ನು ಆರಿಸಿ",
        "role-farmer": "ರೈತ",
        "role-worker": "ಕಾರ್ಮಿಕ",
        "role-shopkeeper": "ವ್ಯಾಪಾರಿ",
        "btn-login": "ಲಾಗಿನ್ ಮಾಡಿ",
        "btn-signup": "ಖಾತೆಯನ್ನು ರಚಿಸಿ",
        "btn-logout": "ಸೈನ್ ಆಫ್ ಮಾಡಿ",
        "email-label": "ಇಮೇಲ್ ವಿಳಾಸ",
        "password-label": "ಪಾಸ್‌ವರ್ಡ್",
        "toggle-signup": "ಖಾತೆ ಇಲ್ಲವೇ? ಸೈನ್ ಅಪ್ ಮಾಡಿ",
        "toggle-login": "ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ? ಲಾಗಿನ್ ಮಾಡಿ",
        "auth-title": "ಹಾರ್ವೆಸ್ಟ್ ಹೈವ್‌ಗೆ ಸೇರಿ",
        "home-title": "ಏಲಕ್ಕಿ ಪರಿಸರ ವ್ಯವಸ್ಥೆ",
        "home-sub": "ತಂತ್ರಜ್ಞಾನದೊಂದಿಗೆ ಪಶ್ಚಿಮ ಘಟ್ಟಗಳ ಕೃಷಿ ಸಮುದಾಯವನ್ನು ಸಬಲೀಕರಣಗೊಳಿಸುವುದು.",
        "about-cardamom-title": "ಮಸಾಲೆಗಳ ರಾಣಿ",
        "about-cardamom-text": "ಮಸಾಲೆಗಳ ರಾಣಿ ಎಂದು ಕರೆಯಲ್ಪಡುವ ಏಲಕ್ಕಿ ನಮ್ಮ ಪ್ರದೇಶದ ಆರ್ಥಿಕತೆಯ ಹೃದಯವಾಗಿದೆ. ಅವುಗಳನ್ನು ಬೆಳೆಸಲು ನಿಖರತೆ, ಕಾಳಜಿ ಮತ್ತು ಸಮಯೋಚಿತ ಹಸ್ತಕ್ಷೇಪದ ಅಗತ್ಯವಿದೆ.",
        "explore-features": "ನಮ್ಮ ವೈಶಿಷ್ಟ್ಯಗಳನ್ನು ಅನ್ವೇಷಿಸಿ",
        "home-labor-desc": "ಕಾರ್ಮಿಕರು ಮತ್ತು ಸಾರಿಗೆಯನ್ನು ಸುಲಭವಾಗಿ ನಿರ್ವಹಿಸಿ.",
        "home-stock-desc": "ಗೊಬ್ಬರಗಳು ಮತ್ತು ಕೀಟನಾಶಕಗಳ ಬಗ್ಗೆ ನಿಗಾ ಇರಿಸಿ.",
        "home-crop-desc": "AI ಡಯಾಗ್ನೋಸ್ಟಿಕ್ಸ್ನೊಂದಿಗೆ ನಿಮ್ಮ ಇಳುವರಿಯನ್ನು ರಕ್ಷಿಸಿ.",
        "btn-get-started": "ಈಗಲೇ ಪ್ರಾರಂಭಿಸಿ",
        "already-member": "ಈಗಾಗಲೇ ಸದಸ್ಯರೇ?"
    }
};

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
    const [language, setLanguage] = useState<Language>("en");

    const t = (key: string) => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error("useLanguage must be used within a LanguageProvider");
    }
    return context;
}
